services:
  - type: web
    name: ai-real-time-gym-coach
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8501
      - key: GROQ_API_KEY
        sync: false
